import { createFileRoute, Link } from "@tanstack/react-router";
import { EyeOff, HeartHandshake, ShieldCheck, UsersRound } from "lucide-react";
import ownersImage from "@/assets/northline-owners.webp";
import { CtaBand, IconCard, PageHero, SectionHeading } from "@/components/site/ui";

export const Route = createFileRoute("/business-owners")({ head: () => ({ meta: [{ title: "For Business Owners | Northline Capital Partners" }, { name: "description", content: "A thoughtful resource for business owners considering succession, continuity, and a long-term capital partner." }] }), component: Owners });

function Owners() { return <><PageHero eyebrow="For business owners" title="Your Business Is More Than a Transaction" intro="A transition can carry years of work, responsibility, relationships, and identity. The right conversation should respect all of it."><Link to="/contact" className="btn-base btn-primary">Speak With Northline</Link></PageHero>
  <section className="section-y"><div className="container-page grid items-center gap-14 lg:grid-cols-2"><div><SectionHeading eyebrow="What owners weigh" title="Continuity, People, Legacy, and the Next Chapter" intro="Every situation is different. Northline's role is to understand what matters, surface the tradeoffs clearly, and determine whether there is genuine alignment." /><div className="mt-8 grid gap-4 sm:grid-cols-2"><IconCard icon={UsersRound} title="Employees" body="The people and capabilities that sustain the company." /><IconCard icon={HeartHandshake} title="Relationships" body="Customers, suppliers, communities, and trusted advisors." /><IconCard icon={ShieldCheck} title="Legacy" body="The standards, reputation, and values built over time." /><IconCard icon={EyeOff} title="Confidentiality" body="A measured process that respects the sensitivity of early discussions." /></div></div><div className="overflow-hidden rounded-2xl shadow-[var(--shadow-card)]"><img src={ownersImage} alt="Business owner discussing continuity with a small group of operating partners" className="aspect-[4/5] h-full w-full object-cover" /></div></div></section>
  <section className="section-y bg-surface"><div className="container-page"><SectionHeading eyebrow="What to expect" title="A Clear, Respectful First Process" /><div className="mt-10 grid gap-6 md:grid-cols-3"><div className="card-soft"><p className="eyebrow">First</p><h3 className="mt-3 text-xl">A private conversation</h3><p className="mt-3 text-sm leading-7 text-muted-foreground">Share the situation at a high level and ask direct questions about fit.</p></div><div className="card-soft"><p className="eyebrow">Then</p><h3 className="mt-3 text-xl">A mutual assessment</h3><p className="mt-3 text-sm leading-7 text-muted-foreground">Clarify priorities, expectations, and whether it makes sense to continue.</p></div><div className="card-soft"><p className="eyebrow">If aligned</p><h3 className="mt-3 text-xl">A thoughtful next step</h3><p className="mt-3 text-sm leading-7 text-muted-foreground">Agree on the information, timing, and secure process required for deeper review.</p></div></div></div></section><CtaBand title="Start With a Confidential Conversation" />
  </>; }
