import { createFileRoute, Link } from "@tanstack/react-router";
import { Building, CircleDollarSign, Factory, MapPinned } from "lucide-react";
import { ConfirmNote, CtaBand, IconCard, PageHero, SectionHeading } from "@/components/site/ui";

export const Route = createFileRoute("/investment-criteria")({ head: () => ({ meta: [{ title: "Investment Criteria | Northline Capital Partners" }, { name: "description", content: "Review the draft investment-criteria framework for Northline Capital Partners and submit an opportunity." }] }), component: Criteria });

function Criteria() { return <><PageHero eyebrow="Investment criteria" title="A Clear Framework for Potential Fit" intro="This draft page shows how owners and advisors will evaluate fit once Northline's public investment criteria are approved."><Link to="/contact" className="btn-base btn-primary">Submit an Opportunity</Link></PageHero>
  <section className="section-y"><div className="container-page"><ConfirmNote>All criteria below require written approval before publication. No revenue, EBITDA, deal-size, industry, or geography assumptions have been made.</ConfirmNote><div className="mt-10 grid gap-6 md:grid-cols-2"><IconCard icon={Factory} title="Preferred Industries" body="[CONFIRM: approved sectors, exclusions, and any business-model preferences.]" /><IconCard icon={MapPinned} title="Investment Geography" body="[CONFIRM: approved regions, countries, and any location requirements.]" /><IconCard icon={Building} title="Company Profile" body="[CONFIRM: ownership situation, operating characteristics, and qualitative fit.]" /><IconCard icon={CircleDollarSign} title="Financial Criteria" body="[CONFIRM: any revenue, EBITDA, profitability, or transaction range approved for public use.]" /></div></div></section>
  <section className="section-y bg-surface"><div className="container-page grid gap-12 lg:grid-cols-[1fr_1.1fr]"><SectionHeading eyebrow="What helps us begin" title="A Useful First Overview" intro="A short, non-sensitive description is enough for an initial conversation. Detailed confidential materials should be exchanged only through an approved secure process." /><div className="card-soft"><h2 className="text-2xl">Helpful context</h2><ul className="mt-6 space-y-4 text-sm leading-7 text-muted-foreground"><li>• Company and industry overview</li><li>• General location and ownership context</li><li>• Reason for exploring a partnership</li><li>• Preferred timing and contact method</li></ul></div></div></section><CtaBand title="Have an Opportunity to Discuss?" />
  </>; }
