import { createFileRoute, Link } from "@tanstack/react-router";
import { ChartNoAxesCombined, Compass, Handshake, Search, ShieldCheck, Waypoints } from "lucide-react";
import { CtaBand, IconCard, PageHero, SectionHeading } from "@/components/site/ui";

export const Route = createFileRoute("/investment-approach")({ head: () => ({ meta: [{ title: "Investment Approach | Northline Capital Partners" }, { name: "description", content: "Explore Northline Capital Partners' partnership philosophy, process, and long-term orientation." }] }), component: Approach });

function Approach() { return <><PageHero eyebrow="Investment approach" title="A Partnership Built for the Long Term" intro="Northline's model is grounded in patient decision-making, practical collaboration, and respect for the business that exists today."><Link to="/contact" className="btn-base btn-primary">Start a Confidential Conversation</Link></PageHero>
  <section className="section-y"><div className="container-page"><SectionHeading eyebrow="Philosophy" title="Capital Is Only Part of the Equation" intro="The strongest partnerships begin with alignment: a shared understanding of priorities, responsibilities, time horizon, and what must be protected as the company evolves." /><div className="mt-12 grid gap-6 md:grid-cols-3"><IconCard icon={ShieldCheck} title="Respect the foundation" body="Understand the people, customer relationships, culture, and operating strengths already in place." /><IconCard icon={Compass} title="Align on direction" body="Clarify the desired outcome and the practical path required to move toward it." /><IconCard icon={Handshake} title="Work as partners" body="Define expectations clearly and approach important decisions with candor and discipline." /></div></div></section>
  <section className="section-y bg-surface"><div className="container-page"><SectionHeading eyebrow="Process" title="From First Conversation to Shared Direction" /><div className="mt-12 grid gap-6 md:grid-cols-2 lg:grid-cols-4"><IconCard icon={Search} title="Listen & learn" body="Understand the business, the owner's priorities, and the context behind the opportunity." number="01" /><IconCard icon={Compass} title="Assess alignment" body="Explore fit using verified information and Northline's approved criteria." number="02" /><IconCard icon={Waypoints} title="Shape the path" body="Develop a thoughtful structure and a clear view of the transition." number="03" /><IconCard icon={ChartNoAxesCombined} title="Build over time" body="Focus on practical operating support and durable long-term value." number="04" /></div></div></section>
  <section className="section-y"><div className="container-page grid gap-12 lg:grid-cols-2"><div><SectionHeading eyebrow="Value beyond capital" title="Practical Support, Calibrated to the Business" intro="The exact role should be defined with each partnership. Potential areas of collaboration may include strategic priorities, leadership needs, operating cadence, growth initiatives, and access to aligned expertise." /></div><div className="card-soft bg-secondary"><h2 className="text-2xl">Long-term orientation</h2><p className="mt-4 leading-8 text-muted-foreground">Northline's approved holding period, governance model, and operating resources must be confirmed before any specific commitments are stated publicly.</p></div></div></section><CtaBand />
  </>; }
