/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BusinessOwnersRouteImport } from './routes/business-owners'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as InvestmentApproachRouteImport } from './routes/investment-approach'
import { Route as InvestmentCriteriaRouteImport } from './routes/investment-criteria'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as TermsRouteImport } from './routes/terms'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessOwnersRoute = BusinessOwnersRouteImport.update({
  id: '/business-owners',
  path: '/business-owners',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestmentApproachRoute = InvestmentApproachRouteImport.update({
  id: '/investment-approach',
  path: '/investment-approach',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestmentCriteriaRoute = InvestmentCriteriaRouteImport.update({
  id: '/investment-criteria',
  path: '/investment-criteria',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/business-owners': typeof BusinessOwnersRoute
  '/contact': typeof ContactRoute
  '/investment-approach': typeof InvestmentApproachRoute
  '/investment-criteria': typeof InvestmentCriteriaRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms': typeof TermsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/business-owners': typeof BusinessOwnersRoute
  '/contact': typeof ContactRoute
  '/investment-approach': typeof InvestmentApproachRoute
  '/investment-criteria': typeof InvestmentCriteriaRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms': typeof TermsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/business-owners': typeof BusinessOwnersRoute
  '/contact': typeof ContactRoute
  '/investment-approach': typeof InvestmentApproachRoute
  '/investment-criteria': typeof InvestmentCriteriaRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms': typeof TermsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/business-owners'
    | '/contact'
    | '/investment-approach'
    | '/investment-criteria'
    | '/privacy-policy'
    | '/terms'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/business-owners'
    | '/contact'
    | '/investment-approach'
    | '/investment-criteria'
    | '/privacy-policy'
    | '/terms'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/business-owners'
    | '/contact'
    | '/investment-approach'
    | '/investment-criteria'
    | '/privacy-policy'
    | '/terms'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BusinessOwnersRoute: typeof BusinessOwnersRoute
  ContactRoute: typeof ContactRoute
  InvestmentApproachRoute: typeof InvestmentApproachRoute
  InvestmentCriteriaRoute: typeof InvestmentCriteriaRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business-owners': {
      id: '/business-owners'
      path: '/business-owners'
      fullPath: '/business-owners'
      preLoaderRoute: typeof BusinessOwnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investment-approach': {
      id: '/investment-approach'
      path: '/investment-approach'
      fullPath: '/investment-approach'
      preLoaderRoute: typeof InvestmentApproachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investment-criteria': {
      id: '/investment-criteria'
      path: '/investment-criteria'
      fullPath: '/investment-criteria'
      preLoaderRoute: typeof InvestmentCriteriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BusinessOwnersRoute: BusinessOwnersRoute,
  ContactRoute: ContactRoute,
  InvestmentApproachRoute: InvestmentApproachRoute,
  InvestmentCriteriaRoute: InvestmentCriteriaRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
